global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: prometheus
    static_configs:
        - targets: ["localhost:9100","{{lookup('ansible.builtin.file', '/mnt/c/Users/karim/Desktop/Techstarter/gitrepo/teaching/Monitoring/Grafana_Prometheus/terraform_ec2/ip_1')}}"] 

alerting:
  alertmanagers:
    - static_configs:
        - targets:
          - alertmanager:9093
groups:
- name: All Servers Status
  rules:
  # Alert for any instance that is unreachable for >3 minutes.
  - alert: InstanceDown
    expr: up == 0
    for: 3m
    labels:
      severity: page
    annotations:
      summary: "Instance {{ $labels.instance }} down"
      description: "{{ $labels.instance }} of job {{ $labels.job }} has been down for more than 5 minutes."

  # Alert for any instance that has >70% CPU load.
  # - alert: HostHighCpuLoad
  #     expr: (sum by (instance) (avg by (mode, instance) (rate(node_cpu_seconds_total{mode!="idle"}[2m]))) > 0.7) * on(instance) group_left (nodename) node_uname_info{nodename=~".+"}
  #     for: 10m
  #     labels:
  #       severity: warning
  #     annotations:
  #       summary: Host high CPU load (instance {{ $labels.instance }})
  #       description: "CPU load is > 70%\n  VALUE = {{ $value }}\n  LABELS = {{ $labels }}"