instances:
  hosts:
    prometheus:
      ansible_connection: ssh
      ansible_ssh_user: ubuntu
      ansible_host: "{{lookup('ansible.builtin.file', './prometheus_ip')}}"
      ansible_port: 22
      ansible_ssh_private_key_file: /etc/ansible/ssh-october
    ubuntu:
      ansible_connection: ssh
      ansible_ssh_user: ubuntu
      ansible_host: "{{lookup('ansible.builtin.file', './ubuntu_ip')}}"
      ansible_port: 22
      ansible_ssh_private_key_file: /etc/ansible/ssh-october