---
- ansible.builtin.apt:
    name: "*"
    state: latest

- name: create alertmanager directory
  ansible.builtin.file:
    path: '{{ alertmanager_dir }}'
    owner: ubuntu
    group: ubuntu
    state: directory

- name: Download Alertmanager
  ansible.builtin.get_url:
    url: '{{ alertmanager_url }}'
    dest: '{{ alertmanager_dir }}'

- name: Unpack packages
  ansible.builtin.shell: 'sudo tar -xvf {{ alertmanager_dir }}/{{ alertmanager_version }}.tar.gz'

- name: move files
  copy:
    src: "/home/ubuntu/{{ alertmanager_version }}/"
    dest: "{{ alertmanager_bin }}"
    remote_src: yes
  
- name: create configuration file
  template:
    src: templates/alertmanager.yaml.j2
    dest: "{{ alertmanager_bin }}/alertmanager.yml"
    owner: ubuntu
    group: ubuntu
    mode: 0644

- name: create environment file
  copy:
    dest: "{{ alertmanager_bin }}/alertmanager.env"
    content: |
      AWS_ACCESS_KEY_ID={{ aws_access_key }}
      AWS_SECRET_ACCESS_KEY={{ aws_secret_key }}
      AWS_SESSION_TOKEN={{ aws_session_token }}

- name: create service file
  copy:
    dest: "/etc/systemd/system/alertmanager.service"
    content: |
      [Unit]
      Description=Alertmanager Service
      After=network.target

      [Service]
      Type=simple
      ExecStart=/usr/local/bin/alertmanager/alertmanager --config.file=/usr/local/bin/alertmanager/alertmanager.yml EnvironmentFile=/usr/local/bin/alertmanager/alertmanager.env

      [Install]
      WantedBy=multi-user.target


- name: service always started
  systemd:
    name: alertmanager 
    state: restarted
    enabled: true