# Whether to notify about resolved alerts.
# [ send_resolved: <boolean> | default = true ]

# The SNS API URL i.e. https://sns.us-east-2.amazonaws.com.
#  If not specified, the SNS API URL from the SNS SDK will be used.
api_url: {{ sns_api}}

# Configures AWS's Signature Verification 4 signing process to sign requests.
# sigv4:
#   [ <sigv4_config> ]

# SNS topic ARN, i.e. arn:aws:sns:us-east-2:698519295917:My-Topic
# If you don't specify this value, you must specify a value for the phone_number or target_arn.
# If you are using a FIFO SNS topic you should set a message group interval longer than 5 minutes
# to prevent messages with the same group key being deduplicated by the SNS default deduplication window
topic_arn: {{ sns_topic_arn }}

# Subject line when the message is delivered to email endpoints.
subject: 'some alert'

# Phone number if message is delivered via SMS in E.164 format.
# If you don't specify this value, you must specify a value for the topic_arn or target_arn.
# [ phone_number: <tmpl_string> ]

# The  mobile platform endpoint ARN if message is delivered via mobile notifications.
# If you don't specify this value, you must specify a value for the topic_arn or phone_number.
# [ target_arn: <tmpl_string> ]

# The message content of the SNS notification.
message: "some message"

# SNS message attributes.
attributes:
  someAttribute: "someValueForAttribute"

# The HTTP client's configuration.
# [ http_config: <http_config> | default = global.http_config ]