---
- name: Install Monitoring and Alerting
  hosts: prometheus
  roles:
    - role: prometheus
      vars: 
        prometheus_dir: '/home/ubuntu/prometheus'
        prometheus_url: 'https://github.com/prometheus/prometheus/releases/download/v2.47.2/prometheus-2.47.2.linux-amd64.tar.gz'
        prometheus_version: 'prometheus-2.47.2.linux-amd64'
        prometheus_bin: '/usr/local/bin/prometheus'

    - role: alertmanager
      vars:
        alertmanager_dir: '/home/ubuntu/alertmanager'
        alertmanager_url: 'https://github.com/prometheus/alertmanager/releases/download/v0.26.0/alertmanager-0.26.0.linux-amd64.tar.gz'
        alertmanager_version: 'alertmanager-0.26.0.linux-amd64'
        alertmanager_bin: '/usr/local/bin/alertmanager'

        aws_region: 'eu-central-1'
        aws_access_key: ""
        aws_secret_key: ""
        aws_session_token: ""
        aws_role: ""
        aws_profile: ""
        sns_api : 'https://sns.eu-central-1.amazonaws.com'
        sns_topic_arn: "{{lookup('ansible.builtin.file', '/mnt/c/Users/karim/Desktop/Techstarter/gitrepo/teaching/Monitoring/Grafana_Prometheus/terraform_ec2/sns_arn')}}"

    - role: grafana
  become: true
